BEGIN;


CREATE TABLE public.candidates
(
    id integer NOT NULL,
    first_name character varying(35),
    last_name character varying(35),
    identity_number character varying(11),
    birth_year integer,
    verifed_id integer,
    cv_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    city_id integer NOT NULL,
    city_name character(35),
    cities integer,
    PRIMARY KEY (city_id)
);

CREATE TABLE public.cv
(
    cv_id integer NOT NULL,
    school character varying(255),
    department character varying(255),
    first_year integer,
    graduation_year integer,
    last_jobs_name character varying(255),
    last_jobs_position character varying(255),
    jobs_enter_year integer,
    jobs_end_year integer,
    languages_level integer,
    github_link character varying(125),
    linkedln_link character varying(125),
    softwarelang_or_tech bytea,
    candidates_name character varying(255) NOT NULL,
    languages bytea,
    front_title character varying(255),
    unemployed_id integer,
    id integer,
    PRIMARY KEY (cv_id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(255) NOT NULL,
    phone_number character varying(12) NOT NULL,
    jobs_id integer,
    web_adress character varying(255),
    job_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_title
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(255),
    city_id integer,
    "position" character varying(255),
    last_date integer,
    min_salary integer,
    is_job_open boolean,
    max_salary integer,
    job_id integer,
    employers_name character varying(45),
    city_names bytea,
    PRIMARY KEY (id)
);

CREATE TABLE public.personel
(
    id integer NOT NULL,
    first_name character varying(35) NOT NULL,
    last_name character varying(35) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.user_photo
(
    photo_id integer NOT NULL,
    photo_url character varying(255),
    user_id integer,
    id integer NOT NULL,
    PRIMARY KEY (photo_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(320) NOT NULL,
    password character varying(25) NOT NULL,
    user_photo character varying(25),
    PRIMARY KEY (id)
);

CREATE TABLE public.verifed
(
    verifed_id integer NOT NULL,
    verifed boolean,
    verifed_date character(10),
    PRIMARY KEY (verifed_id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.cv (cv_id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (verifed_id)
    REFERENCES public.verifed (verifed_id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.cities
    ADD FOREIGN KEY (cities)
    REFERENCES public.job_title (id)
    NOT VALID;


ALTER TABLE public.cv
    ADD FOREIGN KEY (id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (jobs_id)
    REFERENCES public.job_title (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (job_id)
    REFERENCES public.job_title (id)
    NOT VALID;


ALTER TABLE public.job_title
    ADD FOREIGN KEY (job_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_title
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id)
    NOT VALID;


ALTER TABLE public.personel
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.user_photo
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;